repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: local
    hooks:
      - id: generate-requirements
        name: Generate requirements.txt
        entry: python -c "import subprocess; subprocess.run(['pip', 'freeze', '>', 'requirements.txt'], shell=True)"
        language: system
        types: [python]
